[project]
name = "rmp_backend"
version = "1.0.0"
dependencies = [
    "dotenv>=0.9.9",
    "hf-xet>=1.1.2",
    "numpy>=2.2.6",
    "psycopg2>=2.9.10",
    "pydantic>=2.11.5",
    "scikit-learn>=1.6.1",
    "sqlalchemy>=2.0.41",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
